# vim:ft=python
import os

Import("env")

if env['do_debug']:
    env = env.Clone()
    env.MergeFlags("-g -O0")

utils_obj     = env.SharedObject("utils.c", srcdir=env['pkg_dir'])
msndread      = env.Mex(["read.c", "read_utils.c", utils_obj], srcdir=env['pkg_dir'])
msndblockread = env.Mex(["blockread.c", "audio_files.c", utils_obj],
                        srcdir=env['pkg_dir'])

mfiles = env.Glob(env['pkg_dir'] + os.sep + '*.m', source=False)
target = msndread + msndblockread

Return("target", "mfiles")
