# vim:ft=python
Import(["sndfile", "do_debug"])

if do_debug:
    sndfile = sndfile.Clone()
    if sndfile['PLATFORM'] == "win32":
        sndfile['PDB'] = 'msndread.pdb'
    else:
        sndfile.MergeFlags("-g -O0")

msndread = sndfile.Mex("msndread", ["msndread.c", "utils.c"])

Return("msndread")
