# vim:ft=python
Import(["env", "do_debug"])

if do_debug:
    env = env.Clone()
    if env['PLATFORM'] == "win32":
        env['PDB'] = 'msndread.pdb'
    else:
        env.MergeFlags("-g -O0")

utils_obj     = env.SharedObject("utils.c")
msndread      = env.Mex("msndread", ["msndread.c", utils_obj])
msndblockread = env.Mex("msndblockread", ["msndblockread.c", utils_obj])

Return(["msndread", "msndblockread"])
